/**
 * Génère les manifestes de paquets pour une version publiée : formule
 * Homebrew (packaging/homebrew/cadenas.rb) et manifestes winget
 * (packaging/winget/…). Les empreintes viennent de la release GitHub
 * (SHA256SUMS) et du paquet npm : la version doit donc être publiée.
 *
 * Usage : node scripts/packaging.js [version] [--homebrew | --winget]
 *   version : par défaut, celle de package.json ;
 *   --homebrew, --winget : ne générer que l'un des deux (par défaut : les deux).
 *
 * Publication : automatique à chaque release (workflow release.yml), ou à la
 * main (voir packaging/README.md).
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'PierreEbele/cadenas';
const ROOT = new URL('../', import.meta.url);

const args = process.argv.slice(2);
const only = args.filter((arg) => arg === '--homebrew' || arg === '--winget');
const homebrew = only.length === 0 || only.includes('--homebrew');
const winget = only.length === 0 || only.includes('--winget');
const positional = args.filter((arg) => !arg.startsWith('--'));

const pkg = JSON.parse(await readFile(new URL('package.json', ROOT), 'utf8'));
// La version entre dans des URL : seuls trois nombres en sont retenus.
const parts = /^v?(\d+)\.(\d+)\.(\d+)$/.exec(positional[0] ?? pkg.version);
if (!parts) {
  console.error('Version invalide : attendu X.Y.Z.');
  process.exit(2);
}
const version = parts.slice(1).map(Number).join('.');

async function download(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} : ${response.status} ${response.statusText}`);
  return Buffer.from(await response.arrayBuffer());
}

const releaseUrl = `https://github.com/${REPO}/releases/download/v${version}`;

// Schéma des manifestes winget attendu par microsoft/winget-pkgs.
const MANIFEST_VERSION = '1.12.0';

async function releaseDate() {
  const response = await fetch(`https://api.github.com/repos/${REPO}/releases/tags/v${version}`, {
    headers: { accept: 'application/vnd.github+json' },
  });
  if (!response.ok) throw new Error(`Release v${version} : ${response.status} ${response.statusText}`);
  // La date entre dans un manifeste : seuls l'année, le mois et le jour en
  // sont retenus, en nombres.
  const date = new Date((await response.json()).published_at);
  if (Number.isNaN(date.getTime())) throw new Error(`Release v${version} : date de publication invalide.`);
  const pad = (n) => String(n).padStart(2, '0');
  return `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())}`;
}
/** Empreinte d'un fichier de la release, lue dans son SHA256SUMS. */
async function releaseSum(name) {
  const sums = new Map(
    (await download(`${releaseUrl}/SHA256SUMS`))
      .toString('utf8')
      .trim()
      .split('\n')
      .map((line) => line.trim().split(/\s+\*?/).reverse()),
  );
  const hash = sums.get(name);
  if (!/^[0-9a-f]{64}$/.test(hash ?? '')) throw new Error(`${name} absent de SHA256SUMS`);
  return hash;
}

async function write(path, content) {
  const file = fileURLToPath(new URL(path, ROOT));
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, content);
  console.log(`✔ ${path}`);
}

if (homebrew) {
  // Homebrew : installation depuis le paquet npm, comme les formules Node.js
  // de homebrew-core. Fonctionne sur macOS (Intel et Apple Silicon) et Linux.
  const tarballUrl = `https://registry.npmjs.org/cadenas/-/cadenas-${version}.tgz`;
  const tarballSha = createHash('sha256').update(await download(tarballUrl)).digest('hex');
  await write(
    'packaging/homebrew/cadenas.rb',
    `# Generated by scripts/packaging.js in PierreEbele/cadenas. Do not edit by hand.
class Cadenas < Formula
  desc "Encrypt a file with a password; age-compatible"
  homepage "https://github.com/${REPO}"
  url "${tarballUrl}"
  sha256 "${tarballSha}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/cadenas --version").strip
    (testpath/"password").write "correct horse battery staple\\n"
    (testpath/"note.txt").write "hello"
    system bin/"cadenas", "lock", "--password-file", "password", "note.txt"
    system bin/"cadenas", "unlock", "--password-file", "password", "-o", "out.txt", "note.txt.cadenas"
    assert_equal "hello", (testpath/"out.txt").read
  end
end
`,
  );
}

if (winget) {
  // winget : l'exécutable autonome Windows, installé comme « portable ».
  const id = 'PierreEbele.cadenas';
  const dir = `packaging/winget/manifests/p/PierreEbele/cadenas/${version}`;
  const header = (type) =>
    `# Generated by scripts/packaging.js in PierreEbele/cadenas. Do not edit by hand.\n# yaml-language-server: $schema=https://aka.ms/winget-manifest.${type}.${MANIFEST_VERSION}.schema.json\n`;

  await write(
    `${dir}/${id}.yaml`,
    `${header('version')}
PackageIdentifier: ${id}
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: ${MANIFEST_VERSION}
`,
  );
  await write(
    `${dir}/${id}.installer.yaml`,
    `${header('installer')}
PackageIdentifier: ${id}
PackageVersion: ${version}
InstallerType: portable
ReleaseDate: ${await releaseDate()}
Commands:
  - cadenas
Installers:
  - Architecture: x64
    InstallerUrl: ${releaseUrl}/cadenas-v${version}-windows-x64.exe
    InstallerSha256: ${(await releaseSum(`cadenas-v${version}-windows-x64.exe`)).toUpperCase()}
ManifestType: installer
ManifestVersion: ${MANIFEST_VERSION}
`,
  );
  await write(
    `${dir}/${id}.locale.en-US.yaml`,
    `${header('defaultLocale')}
PackageIdentifier: ${id}
PackageVersion: ${version}
PackageLocale: en-US
Publisher: Pierre Ebele
PublisherUrl: https://github.com/PierreEbele
PackageName: cadenas
PackageUrl: https://github.com/${REPO}
License: MIT
LicenseUrl: https://github.com/${REPO}/blob/v${version}/LICENSE
ShortDescription: Encrypt a file with a password. age-compatible.
Description: |-
  cadenas encrypts and decrypts files with a password: Argon2id and
  XChaCha20-Poly1305, streaming, any file size. It also reads and writes the
  age passphrase format.
Tags:
  - encryption
  - password
  - age
  - cli
ReleaseNotesUrl: https://github.com/${REPO}/releases/tag/v${version}
ManifestType: defaultLocale
ManifestVersion: ${MANIFEST_VERSION}
`,
  );
}
