/**
 * Génère les manifestes de paquets pour une version publiée : formule
 * Homebrew (packaging/homebrew/cadenas.rb) et manifestes winget
 * (packaging/winget/…). Les empreintes viennent de la release GitHub
 * (SHA256SUMS) et du paquet npm : la version doit donc être publiée.
 *
 * Usage : node scripts/packaging.js [version]   (par défaut : package.json)
 *
 * Publication (voir packaging/README.md) : copier la formule dans le dépôt
 * PierreEbele/homebrew-cadenas, et proposer les manifestes winget à
 * microsoft/winget-pkgs.
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'PierreEbele/cadenas';
const ROOT = new URL('../', import.meta.url);

const pkg = JSON.parse(await readFile(new URL('package.json', ROOT), 'utf8'));
// La version entre dans des URL : seuls trois nombres en sont retenus.
const parts = /^v?(\d+)\.(\d+)\.(\d+)$/.exec(process.argv[2] ?? pkg.version);
if (!parts) {
  console.error('Version invalide : attendu X.Y.Z.');
  process.exit(2);
}
const version = parts.slice(1).map(Number).join('.');

async function download(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} : ${response.status} ${response.statusText}`);
  return Buffer.from(await response.arrayBuffer());
}

const releaseUrl = `https://github.com/${REPO}/releases/download/v${version}`;
const sums = new Map(
  (await download(`${releaseUrl}/SHA256SUMS`))
    .toString('utf8')
    .trim()
    .split('\n')
    .map((line) => line.trim().split(/\s+\*?/).reverse()),
);
const sum = (name) => {
  const hash = sums.get(name);
  if (!/^[0-9a-f]{64}$/.test(hash ?? '')) throw new Error(`${name} absent de SHA256SUMS`);
  return hash;
};

const tarballUrl = `https://registry.npmjs.org/cadenas/-/cadenas-${version}.tgz`;
const tarballSha = createHash('sha256').update(await download(tarballUrl)).digest('hex');

async function write(path, content) {
  const file = fileURLToPath(new URL(path, ROOT));
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, content);
  console.log(`✔ ${path}`);
}

// Homebrew : installation depuis le paquet npm, comme les formules Node.js
// de homebrew-core. Fonctionne sur macOS (Intel et Apple Silicon) et Linux.
await write(
  'packaging/homebrew/cadenas.rb',
  `# Generated by scripts/packaging.js in PierreEbele/cadenas. Do not edit by hand.
class Cadenas < Formula
  desc "Encrypt a file with a password; age-compatible"
  homepage "https://github.com/${REPO}"
  url "${tarballUrl}"
  sha256 "${tarballSha}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/cadenas --version").strip
    (testpath/"password").write "correct horse battery staple\\n"
    (testpath/"note.txt").write "hello"
    system bin/"cadenas", "lock", "--password-file", "password", "note.txt"
    system bin/"cadenas", "unlock", "--password-file", "password", "-o", "out.txt", "note.txt.cadenas"
    assert_equal "hello", (testpath/"out.txt").read
  end
end
`,
);

// winget : l'exécutable autonome Windows, installé comme « portable ».
const id = 'PierreEbele.cadenas';
const dir = `packaging/winget/manifests/p/PierreEbele/cadenas/${version}`;
const header = (type) =>
  `# Generated by scripts/packaging.js in PierreEbele/cadenas. Do not edit by hand.\n# yaml-language-server: $schema=https://aka.ms/winget-manifest.${type}.1.9.0.schema.json\n`;

await write(
  `${dir}/${id}.yaml`,
  `${header('version')}
PackageIdentifier: ${id}
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
`,
);
await write(
  `${dir}/${id}.installer.yaml`,
  `${header('installer')}
PackageIdentifier: ${id}
PackageVersion: ${version}
InstallerType: portable
Commands:
  - cadenas
Installers:
  - Architecture: x64
    InstallerUrl: ${releaseUrl}/cadenas-v${version}-windows-x64.exe
    InstallerSha256: ${sum(`cadenas-v${version}-windows-x64.exe`).toUpperCase()}
ManifestType: installer
ManifestVersion: 1.9.0
`,
);
await write(
  `${dir}/${id}.locale.en-US.yaml`,
  `${header('defaultLocale')}
PackageIdentifier: ${id}
PackageVersion: ${version}
PackageLocale: en-US
Publisher: Pierre Ebele
PublisherUrl: https://github.com/PierreEbele
PackageName: cadenas
PackageUrl: https://github.com/${REPO}
License: MIT
LicenseUrl: https://github.com/${REPO}/blob/v${version}/LICENSE
ShortDescription: Encrypt a file with a password. age-compatible.
Description: |-
  cadenas encrypts and decrypts files with a password: Argon2id and
  XChaCha20-Poly1305, streaming, any file size. It also reads and writes the
  age passphrase format.
Tags:
  - encryption
  - password
  - age
  - cli
ReleaseNotesUrl: https://github.com/${REPO}/releases/tag/v${version}
ManifestType: defaultLocale
ManifestVersion: 1.9.0
`,
);
